version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: dockerfile

    container_name: fastapi-dev-env
    
    ports:
      - 8080:80

    volumes:
      - .:/usr/src/app
  

  app:
    image: node:20.3.1-alpine3.18

    container_name: react-dev-env
    

    ports:
      - 3000:3000
      
    volumes:
      - ./app:/home/node/app
    
    working_dir: /home/node/app
    
    command: npm start

